### ISSUE TITLE
Modifying prototypes

### ISSUE THREAD

**Issue by joepie91** [sreenaths/more-js#1]
This library currently modifies prototypes of standard JS objects ("types"), but this is [not a safe thing to do](https://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/). Instead, some sort of wrapper object should be used for this.

**Comment by sreenaths** [comment]
Thank you for the suggestion, @joepie91 
Have published version 0.7 into npm with the option to require each type as an object.

Currently, prototype modification is maintained for backward compatibility. Modification happens only on-demand, and would be deprecated soon.

**Comment by sreenaths** [comment]
Published version 0.7 with the option to "require" each type without modifying the standard JS objects.
Require returns an object of functions.
SHA: 8891f0e620ba2f3c3390ee05c832648e36cfca36
